### ISSUE TITLE
Authentication problems with public images

### ISSUE THREAD

**Issue by weakcamel** [GoogleContainerTools/container-diff#249]
When trying to compare publicly available images, authentication has failed.

```
$ container-diff diff ubuntu:xenial ubuntu:bionic
WARN[0000] Diff may be inaccurate: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: exit status 1 
WARN[0000] Diff may be inaccurate: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: exit status 1 
ERRO[0000] Error getting diff with AptAnalyzer: stat : no such file or directory 
ERRO[0000] Could not retrieve diff: Could not perform diff on {<nil>   []} and {<nil>   []} 
```

Manually asking for an access token with `curl -L https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io
` succeeded without any problems.

Also, problem was gone once I've authenticated using `docker login` with dockerhub; manual workaround with doing `docker pull ubuntu:xenial` and then `container-diff analyze daemon://ubuntu:xenial` did the trick as well.

Is this the intentional behaviour (I well may be missing something very obvious)? and if no, should it perhaps be documented somewhere?

**My environment**

```
$ container-diff version
v0.11.0
$ docker-credential-osxkeychain version
0.6.0
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by dlorenc** [comment]
cc @jonjohnsonjr think we need to do anything in the go-containerregistry library here?

**Comment by jonjohnsonjr** [comment]
Probably related to https://github.com/google/go-containerregistry/issues/233

**Comment by weakcamel** [comment]
Thank you for checking. The symptops are slightly different but indeed, seems like it might be the same root cause. 

I'll be happy to provide any extra data needed.

I'd be happy to have a look at the code if pointed at specific areas, but I don't know Go at all... so it will take some time I admit :)

**Comment by jonjohnsonjr** [comment]
I haven't been able to reproduce this, so it's difficult to debug, but if you don't mind helping a bit I'd really appreciate it.

One place to start would be figuring out what requests and responses we're seeing. I found [this blog post](https://medium.com/@motemen/add-a-single-line-to-your-go-source-and-track-every-http-requests-responses-37f2f15eb72f) super handy.

(I'm assuming you have [golang installed](https://golang.org/doc/install).)

```shell
# Pull down the go-containerregistry package (used by container-diff).
$ go get https://github.com/google/go-containerregistry

# Pull down a package to help us log http requests (per the blog post).
$ go get https://github.com/motemen/go-loghttp
```

Modify the crane command to log the http requests (per the blog post) by importing that package in `cmd/crane/main.go`:
```
diff --git a/cmd/crane/main.go b/cmd/crane/main.go
index a48c6f8..da98a8f 100644
--- a/cmd/crane/main.go
+++ b/cmd/crane/main.go
@@ -19,6 +19,7 @@ import (
        "os"
 
        "github.com/google/go-containerregistry/pkg/crane"
+       _ "github.com/motemen/go-loghttp/global"
 )
 
 func main() {
```

Then run this:
```shell
# Assuming we are in $GOPATH/src/github.com/google/go-containerregistry
# Print the manifest for the image 'ubuntu'.
go run cmd/crane/main.go manifest ubuntu
```

It would be super handy if I could get the output of that both succeeding and failing :) then we'll (hopefully) know where to dig.

I also have a sneaking suspicion that this is related to the osx keychain acting funky. Based on the error you're seeing, we probably need to do something like [this](https://stackoverflow.com/questions/18159704/how-to-debug-exit-status-1-error-when-running-exec-command-in-golang) somewhere around [here](https://github.com/google/go-containerregistry/blob/0eeba96f66fdd1873f2ec7f3764ee3b58c5a050c/pkg/authn/helper.go#L67-L86). I'd love to see both stderr and stdout when that fails or succeeds (but be sure to redact any credentials!).

/cc @shimmerjs @sebgoa if either of you is bored and want to help me debug, since I believe you have both hit this bug :)

**Comment by sebgoa** [comment]
can you give the content of `~/.docker/config.json` when the diff command is failing ?

**Comment by weakcamel** [comment]
Argh! Sorry, I'm no longer able to reproduce this on my machine either. It's as if once I authenticated succesfully - everything clicked.

I've cleared the credential map from `config.json`, removed all local images, checked the keychain (but I  couldn't 't see credentials for the index.docker.io), restarted .. and still, container-diff falls back back to the anonymous mode:

```
$container-diff diff ubuntu:xenial ubuntu:bionic
2018/07/21 09:43:03 No matching credentials found for index.docker.io, falling back on anonymous
2018/07/21 09:43:03 No matching credentials found for index.docker.io, falling back on anonymous

-----Apt-----
...
```

As  issue occured after an (almost) clean OS install, I'll try and get create a new local account and see if that helps.

**Comment by weakcamel** [comment]
Oh my. So, I created a new account. tried to reproduce the issue and still couldn't - sorry.

I guess this issue should be closed just like https://github.com/google/go-containerregistry/issues/233 - unless someone else manages to trigger it.

**Comment by jonjohnsonjr** [comment]
Oh well :-/ thanks for trying!

**Comment by dlorenc** [comment]
Thanks for trying.

**Comment by booninite** [comment]
I've definitely been hitting this.  Will try to find time this week at work and recreate it for this issue.  Please don't interpret my lack of activity as a lack of interest in getting to the bottom of this : )

**Comment by jonjohnsonjr** [comment]
FWIW I believe this was fixed in https://github.com/google/go-containerregistry/pull/258
