### ISSUE TITLE
bug: release artefacts are missing

### ISSUE THREAD

**Issue by mbevc1** [GoogleContainerTools/container-diff#419]
### Expected behavior
Release should contain binary artefacts

### Actual behavior
https://github.com/GoogleContainerTools/container-diff/releases/tag/v0.19.0 is only providing source

**Comment by mbevc1** [comment]
Could we please get this re-released with the missing artefacts?

**Comment by mbevc1** [comment]
If switching I'd suggest using `go-releaser` :)

**Comment by mbevc1** [comment]
@loosebazooka would goreleaser be something you'd be happy to approve?

**Comment by loosebazooka** [comment]
So there are a couple things I'm exploring because:
- The build for this project is already a bit weird, and there are no current "real" maintainers.
- This was a dependency for another project (container-structure-test), but I've removed that dependency and now there aren't any pressing reasons for me to continue to look at this project (and I presume no one else really is).
- I'm thinking about archiving this, rather that letting it fall into a poor state.

Current user options appear to be:
1. See if a more recent, maintained project works for you: [diffoci](https://github.com/reproducible-containers/diffoci)
2. Users fork this and find some active users who can help maintain it.
